// Copyright (c) 2025 Advanced Micro Devices, Inc.
// SPDX-License-Identifier: MIT

/// @file instruction.h
/// @brief Abstract instruction representation with operands, flags, and dynamic state.

#ifndef ROCJITSU_ISA_INSTRUCTION_H_
#define ROCJITSU_ISA_INSTRUCTION_H_

#include "rocjitsu/isa/operand.h"
#include "util/intrusive_list.h"

#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace rocjitsu {

/// @brief Instruction property flags.
enum InstFlags : uint64_t {
  /// @brief Unconditional branch.
  BRANCH = 1,
  /// @brief Conditional branch.
  COND_BRANCH = (1ULL << 1),
  /// @brief Indirect branch (target from register).
  INDIRECT_BRANCH = (1ULL << 2),
  /// @brief Terminates the program.
  PROGRAM_TERMINATOR = (1ULL << 3),
  /// @brief Executes immediately without scheduling latency.
  IMMEDIATELY_EXECUTED = (1ULL << 4),
  /// @brief Memory operation (load or store).
  MEMORY_OP = (1ULL << 5)
};

class BasicBlock;

/// @brief Base class for opaque per-instruction dynamic state.
///
/// @details ISA backends attach subclasses to carry mutable pipeline state (e.g.,
/// computed addresses, response buffers) that lives outside the autogenerated
/// encoding classes. The base class is ISA-neutral.
class DynamicInstState {
public:
  virtual ~DynamicInstState() = default;

  /// @brief Backend-defined tag for pipeline routing or dispatch.
  /// @returns Tag value.
  uint8_t tag() const { return tag_; }

protected:
  uint8_t tag_ = 0;
};

/// @brief Abstract base class that defines the API for an instruction.
class Instruction : public util::IListNode<Instruction, util::IListParent<BasicBlock>> {
public:
  /// @brief Construct an instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic string (e.g. "v_add_f32").
  Instruction(std::string mnemonic) : mnemonic_(std::move(mnemonic)) {}
  virtual ~Instruction() = default;

  Instruction(const Instruction &) = delete;
  Instruction &operator=(const Instruction &) = delete;
  Instruction(Instruction &&) = delete;
  Instruction &operator=(Instruction &&) = delete;

  /// @brief Access the attached dynamic state, or nullptr if none.
  /// @returns Pointer to the dynamic state, or nullptr.
  DynamicInstState *data() { return data_.get(); }
  /// @copydoc data()
  const DynamicInstState *data() const { return data_.get(); }

  /// @brief Typed convenience accessor (unchecked static_cast).
  /// @tparam T Concrete DynamicInstState subclass.
  /// @returns Pointer to the dynamic state cast to @p T.
  template <typename T> T *data_as() {
    assert(dynamic_cast<T *>(data_.get()) != nullptr);
    return static_cast<T *>(data_.get());
  }
  /// @copydoc data_as()
  template <typename T> const T *data_as() const {
    assert(dynamic_cast<const T *>(data_.get()) != nullptr);
    return static_cast<const T *>(data_.get());
  }

  /// @brief Attach dynamic state to this instruction (transfers ownership).
  /// @param[in] d Dynamic state (ownership transferred).
  void set_data(std::unique_ptr<DynamicInstState> d) { data_ = std::move(d); }

  /// @brief The instruction's human-readable mnemonic.
  /// @returns Reference to the mnemonic string.
  const std::string &mnemonic() const { return mnemonic_; }

  /// @brief The instruction's total number of operands.
  /// @returns Sum of source and destination operand counts.
  int num_operands() const { return num_src_operands() + num_dst_operands(); }

  /// @brief The instruction's number of source operands.
  /// @returns Source operand count.
  int num_src_operands() const { return src_operands_.size(); }

  /// @brief The instruction's number of destination operands.
  /// @returns Destination operand count.
  int num_dst_operands() const { return dst_operands_.size(); }

  /// @brief Size of the instruction's encoding in bytes.
  /// @returns Encoding size in bytes.
  int size() const { return size_; }

  /// @brief Whether this instruction is a branch.
  /// @retval true The instruction has the BRANCH flag set.
  /// @retval false The instruction is not a branch.
  bool is_branch() const { return flags_ & BRANCH; }

  /// @brief Whether this instruction is a memory operation.
  /// @retval true The instruction has the MEMORY_OP flag set.
  /// @retval false The instruction is not a memory operation.
  bool is_memory_op() const { return flags_ & MEMORY_OP; }

  /// @brief Produce the disassembly string for this instruction.
  ///
  /// @details On first call, generates and caches the disassembly string. Subsequent
  /// calls return the cached string.
  /// @returns Reference to the disassembly string.
  const std::string &disassemble() const {
    if (disassembly_.empty()) {
      disassembly_ = mnemonic_;
      bool first = true;
      for (auto *opnd : dst_operands_) {
        disassembly_ += (first ? " " : ", ");
        disassembly_ += opnd->name();
        first = false;
      }
      for (auto *opnd : src_operands_) {
        disassembly_ += (first ? " " : ", ");
        disassembly_ += opnd->name();
        first = false;
      }
      if (!modifiers_.empty())
        disassembly_ += modifiers_;
    }
    return disassembly_;
  }

protected:
  /// @brief Size of the instruction's encoding in bytes.
  int size_ = 0;
  /// @brief Instruction's source operands.
  std::vector<Operand *> src_operands_;
  /// @brief Instruction's destination operands.
  std::vector<Operand *> dst_operands_;
  /// @brief Modifier flags appended after operands (e.g. "offset:80 sc0 sc1").
  std::string modifiers_;
  /// @brief Cached disassembly string.
  mutable std::string disassembly_;
  /// @brief Instruction property flags bitmask.
  uint64_t flags_ = 0;
  std::unique_ptr<DynamicInstState> data_;

private:
  const std::string mnemonic_;
};

/// @brief Abstract class that holds static ISA state for a specific instruction instance.
///
/// @details Provides a typed execute() taking the ISA-specific context. Subclasses override
/// this.
/// @tparam Isa ISA traits type providing a Context type alias.
template <typename Isa> class IsaInstruction : public Instruction {
public:
  /// @brief Construct an ISA instruction with the given mnemonic.
  /// @param[in] mnemonic Human-readable mnemonic string.
  IsaInstruction(std::string mnemonic) : Instruction(std::move(mnemonic)) {}

  /// @brief Execute this instruction in the given ISA context.
  /// @param[in,out] ctx ISA-specific execution context (e.g. wavefront state).
  virtual void execute(typename Isa::Context &ctx) = 0;
};

} // namespace rocjitsu

#endif // ROCJITSU_ISA_INSTRUCTION_H_
